{
	name: "ğŸ¥¼ Code Analysis: Prepare",
	on: {
		workflow_call: {
			outputs: {
				preparation-javascript-artifact-identifier: {
					description: "Code analysis preparation artifact identifier for JavaScript and TypeScript",
					value: "${{jobs.code_analysis-prepare.outputs.preparation-javascript-artifact-identifier}}"
				},
				preparation-github_actions-artifact-identifier: {
					description: "Code analysis preparation artifact identifier for GitHub Actions",
					value: "${{jobs.code_analysis-prepare.outputs.preparation-github_actions-artifact-identifier}}"
				}
			}
		}
	},
	
	jobs: {
		code_analysis-prepare: {
			strategy: {
				matrix: {
					include: [
						{
							name: "JavaScript",
							language: "javascript-typescript",
							
							build-mode: "none"
						},
						{
							name: "GitHub Actions",
							language: "actions",
							
							build-mode: "none"
						}
					]
				},
				fail-fast: false
			},
			
			name: "ğŸ¥¼ Code Analysis: Prepare (${{matrix.name}})",
			permissions: {
				contents: "read",
				security-events: "write"
			},
			
			runs-on: "ubuntu-24.04",
			timeout-minutes: 5,
			
			steps: [
				{
					id: "setup-repository_checkout",
					name: "ğŸ—„ï¸ Setup: Repository Checkout",
					
					uses: "actions/checkout@v4.2.2",
					with: {sparse-checkout: ".github"}
				},
				{
					id: "codeql-prepare",
					name: "ğŸ“œ CodeQL: Prepare",
					
					uses: "github/codeql-action/init@v3.28.0",
					with: {
						languages: "${{matrix.language}}",
						build-mode: "${{matrix.build-mode}}",
						# config-file: "?"
						
						dependency-caching: true,
						db-location: "./artifacts/codeql/",
						debug-artifact-name: "debug",
						debug-database-name: "debug-database"
					}
				},
				{
					id: "codeql-product-artifact_upload",
					name: "ğŸ“¤ CodeQL Product: Artifact Upload",
					
					uses: "actions/upload-artifact@v4.5.0",
					with: {name: "ğŸ“œ CodeQL Setup - ${{matrix.name}}", path: "./"}
				}
			],
			outputs: {
				"preparation-javascript-artifact-identifier": "ğŸ“œ CodeQL Setup - JavaScript",
				"preparation-github_actions-artifact-identifier": "ğŸ“œ CodeQL Setup - GitHub Actions"
			}
		}
	}
}